"""module2 recruitment hiring termination

Revision ID: 0004_module2
Revises: 0003_drop_business_processes
Create Date: 2026-07-15 18:31:11.856187
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0004_module2"
down_revision: str | None = "0003_drop_business_processes"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candidates",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(length=160), nullable=False),
        sa.Column("last_name", sa.String(length=160), nullable=False),
        sa.Column("middle_name", sa.String(length=160), nullable=True),
        sa.Column("display_name", sa.String(length=500), nullable=False),
        sa.Column("protected_personal_email", sa.Text(), nullable=True),
        sa.Column("protected_phone", sa.Text(), nullable=True),
        sa.Column("protected_identity", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("consent_status", sa.String(length=30), nullable=False),
        sa.Column("consent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retention_until", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("anonymized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_candidates_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidates")),
    )
    op.create_index(
        "ix_candidates_org_status", "candidates", ["organization_id", "status"], unique=False
    )
    op.create_table(
        "document_types",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("default_confidentiality", sa.String(length=30), nullable=False),
        sa.Column("allowed_mime_types", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("maximum_size_bytes", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_document_types_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_types")),
        sa.UniqueConstraint(
            "organization_id", "code", name=op.f("uq_document_types_organization_id_code")
        ),
    )
    op.create_index(
        op.f("ix_document_types_organization_id"),
        "document_types",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "form_definitions",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_form_definitions_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_form_definitions")),
        sa.UniqueConstraint(
            "organization_id", "code", name=op.f("uq_form_definitions_organization_id_code")
        ),
    )
    op.create_table(
        "process_definitions",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_process_definitions_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_process_definitions")),
        sa.UniqueConstraint(
            "organization_id", "code", name=op.f("uq_process_definitions_organization_id_code")
        ),
    )
    op.create_index(
        op.f("ix_process_definitions_organization_id"),
        "process_definitions",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "termination_reasons",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("legal_review_required", sa.Boolean(), nullable=False),
        sa.Column("employee_initiated", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_termination_reasons_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_termination_reasons")),
        sa.UniqueConstraint(
            "organization_id", "code", name=op.f("uq_termination_reasons_organization_id_code")
        ),
    )
    op.create_table(
        "vacancy_publication_channels",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("channel_type", sa.String(length=50), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_vacancy_publication_channels_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vacancy_publication_channels")),
        sa.UniqueConstraint(
            "organization_id",
            "code",
            name=op.f("uq_vacancy_publication_channels_organization_id_code"),
        ),
    )
    op.create_table(
        "document_templates",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("document_type_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_type_id"],
            ["document_types.id"],
            name=op.f("fk_document_templates_document_type_id_document_types"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_document_templates_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_templates")),
        sa.UniqueConstraint(
            "organization_id", "code", name=op.f("uq_document_templates_organization_id_code")
        ),
    )
    op.create_index(
        op.f("ix_document_templates_organization_id"),
        "document_templates",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "document_template_versions",
        sa.Column("template_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("based_on_version_id", sa.UUID(), nullable=True),
        sa.Column("storage_key", sa.String(length=1000), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("variable_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("published_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["based_on_version_id"],
            ["document_template_versions.id"],
            name=op.f(
                "fk_document_template_versions_based_on_version_id_document_template_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user_accounts.id"],
            name=op.f("fk_document_template_versions_created_by_user_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["published_by"],
            ["user_accounts.id"],
            name=op.f("fk_document_template_versions_published_by_user_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["document_templates.id"],
            name=op.f("fk_document_template_versions_template_id_document_templates"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_template_versions")),
        sa.UniqueConstraint(
            "template_id",
            "version_number",
            name=op.f("uq_document_template_versions_template_id_version_number"),
        ),
    )
    op.create_index(
        op.f("ix_document_template_versions_template_id"),
        "document_template_versions",
        ["template_id"],
        unique=False,
    )
    op.create_table(
        "form_definition_versions",
        sa.Column("form_definition_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("based_on_version_id", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("published_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["based_on_version_id"],
            ["form_definition_versions.id"],
            name=op.f("fk_form_definition_versions_based_on_version_id_form_definition_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user_accounts.id"],
            name=op.f("fk_form_definition_versions_created_by_user_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["form_definition_id"],
            ["form_definitions.id"],
            name=op.f("fk_form_definition_versions_form_definition_id_form_definitions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["published_by"],
            ["user_accounts.id"],
            name=op.f("fk_form_definition_versions_published_by_user_accounts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_form_definition_versions")),
        sa.UniqueConstraint(
            "form_definition_id",
            "version_number",
            name=op.f("uq_form_definition_versions_form_definition_id_version_number"),
        ),
    )
    op.create_table(
        "process_definition_versions",
        sa.Column("process_definition_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("based_on_version_id", sa.UUID(), nullable=True),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("published_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "version_number > 0", name=op.f("ck_process_definition_versions_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["based_on_version_id"],
            ["process_definition_versions.id"],
            name=op.f(
                "fk_process_definition_versions_based_on_version_id_process_definition_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user_accounts.id"],
            name=op.f("fk_process_definition_versions_created_by_user_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["process_definition_id"],
            ["process_definitions.id"],
            name=op.f("fk_process_definition_versions_process_definition_id_process_definitions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["published_by"],
            ["user_accounts.id"],
            name=op.f("fk_process_definition_versions_published_by_user_accounts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_process_definition_versions")),
        sa.UniqueConstraint(
            "process_definition_id",
            "version_number",
            name=op.f("uq_process_definition_versions_process_definition_id_version_number"),
        ),
    )
    op.create_index(
        "ix_process_definition_versions_effective",
        "process_definition_versions",
        ["process_definition_id", "status", "effective_from"],
        unique=False,
    )
    op.create_index(
        op.f("ix_process_definition_versions_process_definition_id"),
        "process_definition_versions",
        ["process_definition_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_process_definition_versions_status"),
        "process_definition_versions",
        ["status"],
        unique=False,
    )
    op.create_table(
        "form_field_definitions",
        sa.Column("form_version_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("label", sa.String(length=300), nullable=False),
        sa.Column("field_type", sa.String(length=50), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("validation_rules", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reference_data_source", sa.String(length=200), nullable=True),
        sa.Column("visibility_rule", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("editability_rule", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("confidentiality", sa.String(length=30), nullable=False),
        sa.Column("ordering", sa.Integer(), nullable=False),
        sa.Column("help_text", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["form_version_id"],
            ["form_definition_versions.id"],
            name=op.f("fk_form_field_definitions_form_version_id_form_definition_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_form_field_definitions")),
        sa.UniqueConstraint(
            "form_version_id", "code", name=op.f("uq_form_field_definitions_form_version_id_code")
        ),
    )
    op.create_table(
        "process_instances",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("process_definition_id", sa.UUID(), nullable=False),
        sa.Column("definition_version_id", sa.UUID(), nullable=False),
        sa.Column("business_type", sa.String(length=100), nullable=False),
        sa.Column("business_entity_id", sa.UUID(), nullable=False),
        sa.Column("initiator_user_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("current_phase", sa.String(length=100), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["definition_version_id"],
            ["process_definition_versions.id"],
            name=op.f("fk_process_instances_definition_version_id_process_definition_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["initiator_user_id"],
            ["user_accounts.id"],
            name=op.f("fk_process_instances_initiator_user_id_user_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_process_instances_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["process_definition_id"],
            ["process_definitions.id"],
            name=op.f("fk_process_instances_process_definition_id_process_definitions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_process_instances")),
    )
    op.create_index(
        "ix_process_instances_business",
        "process_instances",
        ["business_type", "business_entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_process_instances_organization_id"),
        "process_instances",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_process_instances_scope_status",
        "process_instances",
        ["organization_id", "status", "started_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_process_instances_status"), "process_instances", ["status"], unique=False
    )
    op.create_table(
        "workflow_actor_rules",
        sa.Column("definition_version_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("rule_type", sa.String(length=50), nullable=False),
        sa.Column("configuration", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["definition_version_id"],
            ["process_definition_versions.id"],
            name=op.f("fk_workflow_actor_rules_definition_version_id_process_definition_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_actor_rules")),
        sa.UniqueConstraint(
            "definition_version_id",
            "code",
            name=op.f("uq_workflow_actor_rules_definition_version_id_code"),
        ),
    )
    op.create_index(
        op.f("ix_workflow_actor_rules_definition_version_id"),
        "workflow_actor_rules",
        ["definition_version_id"],
        unique=False,
    )
    op.create_table(
        "document_records",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("document_type_id", sa.UUID(), nullable=False),
        sa.Column("template_version_id", sa.UUID(), nullable=True),
        sa.Column("process_instance_id", sa.UUID(), nullable=True),
        sa.Column("business_entity_type", sa.String(length=100), nullable=False),
        sa.Column("business_entity_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("registration_number", sa.String(length=200), nullable=True),
        sa.Column("registration_date", sa.Date(), nullable=True),
        sa.Column("current_version_number", sa.Integer(), nullable=False),
        sa.Column("confidentiality_level", sa.String(length=30), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user_accounts.id"],
            name=op.f("fk_document_records_created_by_user_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["document_type_id"],
            ["document_types.id"],
            name=op.f("fk_document_records_document_type_id_document_types"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_document_records_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["process_instance_id"],
            ["process_instances.id"],
            name=op.f("fk_document_records_process_instance_id_process_instances"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["template_version_id"],
            ["document_template_versions.id"],
            name=op.f("fk_document_records_template_version_id_document_template_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_records")),
    )
    op.create_index(
        "ix_document_records_business",
        "document_records",
        ["business_entity_type", "business_entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_records_organization_id"),
        "document_records",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_document_records_process",
        "document_records",
        ["process_instance_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_records_status"), "document_records", ["status"], unique=False
    )
    op.create_table(
        "form_submissions",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("form_version_id", sa.UUID(), nullable=False),
        sa.Column("process_instance_id", sa.UUID(), nullable=True),
        sa.Column("business_entity_type", sa.String(length=100), nullable=False),
        sa.Column("business_entity_id", sa.UUID(), nullable=False),
        sa.Column("submitted_by", sa.UUID(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["form_version_id"],
            ["form_definition_versions.id"],
            name=op.f("fk_form_submissions_form_version_id_form_definition_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_form_submissions_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["process_instance_id"],
            ["process_instances.id"],
            name=op.f("fk_form_submissions_process_instance_id_process_instances"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by"],
            ["user_accounts.id"],
            name=op.f("fk_form_submissions_submitted_by_user_accounts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_form_submissions")),
    )
    op.create_index(
        "ix_form_submissions_business",
        "form_submissions",
        ["business_entity_type", "business_entity_id"],
        unique=False,
    )
    op.create_table(
        "process_history_entries",
        sa.Column("process_instance_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("summary", sa.String(length=1000), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["user_accounts.id"],
            name=op.f("fk_process_history_entries_actor_user_id_user_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["process_instance_id"],
            ["process_instances.id"],
            name=op.f("fk_process_history_entries_process_instance_id_process_instances"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_process_history_entries")),
    )
    op.create_index(
        op.f("ix_process_history_entries_process_instance_id"),
        "process_history_entries",
        ["process_instance_id"],
        unique=False,
    )
    op.create_index(
        "ix_process_history_instance_time",
        "process_history_entries",
        ["process_instance_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "process_step_definitions",
        sa.Column("definition_version_id", sa.UUID(), nullable=False),
        sa.Column("stable_key", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("step_type", sa.String(length=50), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("actor_rule_id", sa.UUID(), nullable=True),
        sa.Column("allowed_actions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("due_duration_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "required_document_type_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("configuration", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("completion_mode", sa.String(length=10), nullable=False),
        sa.Column("required_approvers", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "required_approvers > 0",
            name=op.f("ck_process_step_definitions_required_approvers_positive"),
        ),
        sa.CheckConstraint(
            "sequence >= 0", name=op.f("ck_process_step_definitions_sequence_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["actor_rule_id"],
            ["workflow_actor_rules.id"],
            name=op.f("fk_process_step_definitions_actor_rule_id_workflow_actor_rules"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["definition_version_id"],
            ["process_definition_versions.id"],
            name=op.f(
                "fk_process_step_definitions_definition_version_id_process_definition_versions"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_process_step_definitions")),
        sa.UniqueConstraint(
            "definition_version_id",
            "code",
            name=op.f("uq_process_step_definitions_definition_version_id_code"),
        ),
        sa.UniqueConstraint(
            "definition_version_id",
            "stable_key",
            name=op.f("uq_process_step_definitions_definition_version_id_stable_key"),
        ),
    )
    op.create_index(
        op.f("ix_process_step_definitions_definition_version_id"),
        "process_step_definitions",
        ["definition_version_id"],
        unique=False,
    )
    op.create_table(
        "competition_commissions",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("meeting_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("quorum_required", sa.Integer(), nullable=False),
        sa.Column("protocol_document_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_competition_commissions_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["protocol_document_id"],
            ["document_records.id"],
            name=op.f("fk_competition_commissions_protocol_document_id_document_records"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competition_commissions")),
    )
    op.create_table(
        "document_checklist_items",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("process_instance_id", sa.UUID(), nullable=True),
        sa.Column("business_entity_type", sa.String(length=100), nullable=False),
        sa.Column("business_entity_id", sa.UUID(), nullable=False),
        sa.Column("document_type_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("mandatory", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("rejection_comment", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document_records.id"],
            name=op.f("fk_document_checklist_items_document_id_document_records"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["document_type_id"],
            ["document_types.id"],
            name=op.f("fk_document_checklist_items_document_type_id_document_types"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_document_checklist_items_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["process_instance_id"],
            ["process_instances.id"],
            name=op.f("fk_document_checklist_items_process_instance_id_process_instances"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_checklist_items")),
        sa.UniqueConstraint(
            "business_entity_type",
            "business_entity_id",
            "document_type_id",
            name=op.f(
                "uq_document_checklist_items_business_entity_type_business_entity_id_document_type_id"
            ),
        ),
    )
    op.create_table(
        "document_versions",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("storage_key", sa.String(length=1000), nullable=False),
        sa.Column("original_filename", sa.String(length=500), nullable=False),
        sa.Column("safe_filename", sa.String(length=500), nullable=False),
        sa.Column("mime_type", sa.String(length=200), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("author_user_id", sa.UUID(), nullable=False),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("immutable", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint("size_bytes >= 0", name=op.f("ck_document_versions_size_nonnegative")),
        sa.ForeignKeyConstraint(
            ["author_user_id"],
            ["user_accounts.id"],
            name=op.f("fk_document_versions_author_user_id_user_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document_records.id"],
            name=op.f("fk_document_versions_document_id_document_records"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_versions")),
        sa.UniqueConstraint(
            "document_id",
            "version_number",
            name=op.f("uq_document_versions_document_id_version_number"),
        ),
        sa.UniqueConstraint("storage_key", name=op.f("uq_document_versions_storage_key")),
    )
    op.create_index(
        op.f("ix_document_versions_document_id"), "document_versions", ["document_id"], unique=False
    )
    op.create_table(
        "process_transition_definitions",
        sa.Column("definition_version_id", sa.UUID(), nullable=False),
        sa.Column("source_step_id", sa.UUID(), nullable=False),
        sa.Column("target_step_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.String(length=30), nullable=False),
        sa.Column("condition", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["definition_version_id"],
            ["process_definition_versions.id"],
            name=op.f(
                "fk_process_transition_definitions_definition_version_id_process_definition_versions"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_step_id"],
            ["process_step_definitions.id"],
            name=op.f("fk_process_transition_definitions_source_step_id_process_step_definitions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_step_id"],
            ["process_step_definitions.id"],
            name=op.f("fk_process_transition_definitions_target_step_id_process_step_definitions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_process_transition_definitions")),
        sa.UniqueConstraint(
            "definition_version_id",
            "source_step_id",
            "target_step_id",
            "action",
            name=op.f(
                "uq_process_transition_definitions_definition_version_id_source_step_id_target_step_id_action"
            ),
        ),
    )
    op.create_index(
        op.f("ix_process_transition_definitions_definition_version_id"),
        "process_transition_definitions",
        ["definition_version_id"],
        unique=False,
    )
    op.create_table(
        "recruitment_requests",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("requesting_unit_id", sa.UUID(), nullable=False),
        sa.Column("requested_by_employee_id", sa.Uuid(), nullable=False),
        sa.Column("staffing_slot_id", sa.UUID(), nullable=True),
        sa.Column("position_definition_id", sa.UUID(), nullable=False),
        sa.Column("requested_fte", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("employment_type", sa.String(length=50), nullable=False),
        sa.Column("desired_start_date", sa.Date(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("responsibilities", sa.Text(), nullable=False),
        sa.Column("requirements", sa.Text(), nullable=False),
        sa.Column("proposed_compensation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("process_instance_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_recruitment_requests_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["position_definition_id"],
            ["position_definitions.id"],
            name=op.f("fk_recruitment_requests_position_definition_id_position_definitions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["process_instance_id"],
            ["process_instances.id"],
            name=op.f("fk_recruitment_requests_process_instance_id_process_instances"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_employee_id"],
            ["employees.id"],
            name=op.f("fk_recruitment_requests_requested_by_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requesting_unit_id"],
            ["organization_units.id"],
            name=op.f("fk_recruitment_requests_requesting_unit_id_organization_units"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["staffing_slot_id"],
            ["staffing_slots.id"],
            name=op.f("fk_recruitment_requests_staffing_slot_id_staffing_slots"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recruitment_requests")),
    )
    op.create_index(
        op.f("ix_recruitment_requests_organization_id"),
        "recruitment_requests",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recruitment_requests_requesting_unit_id"),
        "recruitment_requests",
        ["requesting_unit_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recruitment_requests_status"), "recruitment_requests", ["status"], unique=False
    )
    op.create_table(
        "workflow_tasks",
        sa.Column("process_instance_id", sa.UUID(), nullable=False),
        sa.Column("step_definition_id", sa.UUID(), nullable=False),
        sa.Column("assigned_user_id", sa.UUID(), nullable=True),
        sa.Column("assigned_employee_id", sa.Uuid(), nullable=True),
        sa.Column("assigned_unit_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision", sa.String(length=30), nullable=True),
        sa.Column("decision_comment", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_employee_id"],
            ["employees.id"],
            name=op.f("fk_workflow_tasks_assigned_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["assigned_unit_id"],
            ["organization_units.id"],
            name=op.f("fk_workflow_tasks_assigned_unit_id_organization_units"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["assigned_user_id"],
            ["user_accounts.id"],
            name=op.f("fk_workflow_tasks_assigned_user_id_user_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["process_instance_id"],
            ["process_instances.id"],
            name=op.f("fk_workflow_tasks_process_instance_id_process_instances"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["step_definition_id"],
            ["process_step_definitions.id"],
            name=op.f("fk_workflow_tasks_step_definition_id_process_step_definitions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_tasks")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_workflow_tasks_idempotency_key")),
        sa.UniqueConstraint(
            "process_instance_id",
            "step_definition_id",
            "assigned_user_id",
            name="uq_workflow_task_assignment",
        ),
    )
    op.create_index(
        "ix_workflow_tasks_assigned",
        "workflow_tasks",
        ["assigned_user_id", "status", "due_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_tasks_assigned_user_id"),
        "workflow_tasks",
        ["assigned_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_tasks_process_instance_id"),
        "workflow_tasks",
        ["process_instance_id"],
        unique=False,
    )
    op.create_index(op.f("ix_workflow_tasks_status"), "workflow_tasks", ["status"], unique=False)
    op.create_table(
        "competition_commission_members",
        sa.Column("commission_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.Column("conflict_declared", sa.Boolean(), nullable=False),
        sa.Column("declaration", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["commission_id"],
            ["competition_commissions.id"],
            name=op.f("fk_competition_commission_members_commission_id_competition_commissions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_competition_commission_members_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competition_commission_members")),
        sa.UniqueConstraint(
            "commission_id",
            "employee_id",
            name=op.f("uq_competition_commission_members_commission_id_employee_id"),
        ),
    )
    op.create_table(
        "document_acknowledgements",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("document_version_id", sa.UUID(), nullable=False),
        sa.Column("assigned_employee_id", sa.Uuid(), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("evidence_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_employee_id"],
            ["employees.id"],
            name=op.f("fk_document_acknowledgements_assigned_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document_records.id"],
            name=op.f("fk_document_acknowledgements_document_id_document_records"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["document_versions.id"],
            name=op.f("fk_document_acknowledgements_document_version_id_document_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_acknowledgements")),
        sa.UniqueConstraint(
            "document_version_id",
            "assigned_employee_id",
            name=op.f("uq_document_acknowledgements_document_version_id_assigned_employee_id"),
        ),
    )
    op.create_table(
        "document_signatures",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("document_version_id", sa.UUID(), nullable=False),
        sa.Column("signer_user_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("provider_reference", sa.String(length=500), nullable=True),
        sa.Column("manual_confirmation", sa.Boolean(), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("evidence_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document_records.id"],
            name=op.f("fk_document_signatures_document_id_document_records"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["document_versions.id"],
            name=op.f("fk_document_signatures_document_version_id_document_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["signer_user_id"],
            ["user_accounts.id"],
            name=op.f("fk_document_signatures_signer_user_id_user_accounts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_signatures")),
    )
    op.create_index(
        "ix_document_signatures_document",
        "document_signatures",
        ["document_id", "status"],
        unique=False,
    )
    op.create_table(
        "recruitment_staffing_reviews",
        sa.Column("recruitment_request_id", sa.UUID(), nullable=False),
        sa.Column("reviewer_user_id", sa.UUID(), nullable=False),
        sa.Column("vacant_slot_confirmed", sa.Boolean(), nullable=False),
        sa.Column("approved_fte", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("budget_confirmed", sa.Boolean(), nullable=False),
        sa.Column("compensation_range", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("decision", sa.String(length=30), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recruitment_request_id"],
            ["recruitment_requests.id"],
            name=op.f(
                "fk_recruitment_staffing_reviews_recruitment_request_id_recruitment_requests"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_user_id"],
            ["user_accounts.id"],
            name=op.f("fk_recruitment_staffing_reviews_reviewer_user_id_user_accounts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recruitment_staffing_reviews")),
        sa.UniqueConstraint(
            "recruitment_request_id",
            name=op.f("uq_recruitment_staffing_reviews_recruitment_request_id"),
        ),
    )
    op.create_table(
        "termination_cases",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("initiated_by_user_id", sa.UUID(), nullable=False),
        sa.Column("initiated_by_employee_id", sa.Uuid(), nullable=True),
        sa.Column("reason_id", sa.UUID(), nullable=False),
        sa.Column("legal_basis", sa.Text(), nullable=False),
        sa.Column("requested_date", sa.Date(), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("process_instance_id", sa.UUID(), nullable=True),
        sa.Column("order_document_id", sa.UUID(), nullable=True),
        sa.Column("primary_assignment_id", sa.Uuid(), nullable=True),
        sa.Column(
            "secondary_assignment_plan", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("manager_notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancellation_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_termination_cases_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["initiated_by_employee_id"],
            ["employees.id"],
            name=op.f("fk_termination_cases_initiated_by_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["initiated_by_user_id"],
            ["user_accounts.id"],
            name=op.f("fk_termination_cases_initiated_by_user_id_user_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_document_id"],
            ["document_records.id"],
            name=op.f("fk_termination_cases_order_document_id_document_records"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_termination_cases_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["primary_assignment_id"],
            ["employee_assignments.id"],
            name=op.f("fk_termination_cases_primary_assignment_id_employee_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["process_instance_id"],
            ["process_instances.id"],
            name=op.f("fk_termination_cases_process_instance_id_process_instances"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reason_id"],
            ["termination_reasons.id"],
            name=op.f("fk_termination_cases_reason_id_termination_reasons"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_termination_cases")),
    )
    op.create_index(
        op.f("ix_termination_cases_employee_id"), "termination_cases", ["employee_id"], unique=False
    )
    op.create_index(
        op.f("ix_termination_cases_organization_id"),
        "termination_cases",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_termination_cases_scope_status",
        "termination_cases",
        ["organization_id", "status", "effective_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_termination_cases_status"), "termination_cases", ["status"], unique=False
    )
    op.create_table(
        "vacancies",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("recruitment_request_id", sa.UUID(), nullable=False),
        sa.Column("staffing_slot_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("responsibilities", sa.Text(), nullable=False),
        sa.Column("requirements", sa.Text(), nullable=False),
        sa.Column("employment_conditions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("publication_status", sa.String(length=40), nullable=False),
        sa.Column("internal_published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("external_published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("application_deadline", sa.Date(), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("close_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_vacancies_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recruitment_request_id"],
            ["recruitment_requests.id"],
            name=op.f("fk_vacancies_recruitment_request_id_recruitment_requests"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["staffing_slot_id"],
            ["staffing_slots.id"],
            name=op.f("fk_vacancies_staffing_slot_id_staffing_slots"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vacancies")),
        sa.UniqueConstraint(
            "organization_id", "code", name=op.f("uq_vacancies_organization_id_code")
        ),
    )
    op.create_index(
        op.f("ix_vacancies_organization_id"), "vacancies", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_vacancies_publication_status"), "vacancies", ["publication_status"], unique=False
    )
    op.create_table(
        "candidate_applications",
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("vacancy_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("current_stage", sa.String(length=40), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("withdrawn_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejection_reason_code", sa.String(length=100), nullable=True),
        sa.Column("rejection_comment", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
            name=op.f("fk_candidate_applications_candidate_id_candidates"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vacancy_id"],
            ["vacancies.id"],
            name=op.f("fk_candidate_applications_vacancy_id_vacancies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate_applications")),
        sa.UniqueConstraint(
            "candidate_id",
            "vacancy_id",
            name=op.f("uq_candidate_applications_candidate_id_vacancy_id"),
        ),
    )
    op.create_index(
        op.f("ix_candidate_applications_candidate_id"),
        "candidate_applications",
        ["candidate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_candidate_applications_status"), "candidate_applications", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_candidate_applications_vacancy_id"),
        "candidate_applications",
        ["vacancy_id"],
        unique=False,
    )
    op.create_table(
        "offboarding_tasks",
        sa.Column("termination_case_id", sa.UUID(), nullable=False),
        sa.Column("task_type", sa.String(length=50), nullable=False),
        sa.Column("assigned_user_id", sa.UUID(), nullable=True),
        sa.Column("assigned_employee_id", sa.Uuid(), nullable=True),
        sa.Column("assigned_unit_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("restricted_notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_employee_id"],
            ["employees.id"],
            name=op.f("fk_offboarding_tasks_assigned_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["assigned_unit_id"],
            ["organization_units.id"],
            name=op.f("fk_offboarding_tasks_assigned_unit_id_organization_units"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["assigned_user_id"],
            ["user_accounts.id"],
            name=op.f("fk_offboarding_tasks_assigned_user_id_user_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["termination_case_id"],
            ["termination_cases.id"],
            name=op.f("fk_offboarding_tasks_termination_case_id_termination_cases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offboarding_tasks")),
        sa.UniqueConstraint(
            "termination_case_id",
            "task_type",
            name=op.f("uq_offboarding_tasks_termination_case_id_task_type"),
        ),
    )
    op.create_index(
        op.f("ix_offboarding_tasks_termination_case_id"),
        "offboarding_tasks",
        ["termination_case_id"],
        unique=False,
    )
    op.create_table(
        "vacancy_publications",
        sa.Column("vacancy_id", sa.UUID(), nullable=False),
        sa.Column("channel_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("external_reference", sa.String(length=1000), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("responsible_employee_id", sa.Uuid(), nullable=False),
        sa.Column("manual", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["vacancy_publication_channels.id"],
            name=op.f("fk_vacancy_publications_channel_id_vacancy_publication_channels"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["responsible_employee_id"],
            ["employees.id"],
            name=op.f("fk_vacancy_publications_responsible_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vacancy_id"],
            ["vacancies.id"],
            name=op.f("fk_vacancy_publications_vacancy_id_vacancies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vacancy_publications")),
        sa.UniqueConstraint(
            "vacancy_id", "channel_id", name=op.f("uq_vacancy_publications_vacancy_id_channel_id")
        ),
    )
    op.create_table(
        "candidate_screenings",
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("reviewer_user_id", sa.UUID(), nullable=False),
        sa.Column("criteria_results", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("decision", sa.String(length=30), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["candidate_applications.id"],
            name=op.f("fk_candidate_screenings_application_id_candidate_applications"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_user_id"],
            ["user_accounts.id"],
            name=op.f("fk_candidate_screenings_reviewer_user_id_user_accounts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate_screenings")),
    )
    op.create_index(
        op.f("ix_candidate_screenings_application_id"),
        "candidate_screenings",
        ["application_id"],
        unique=False,
    )
    op.create_table(
        "competition_commission_decisions",
        sa.Column("commission_id", sa.UUID(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("decision", sa.String(length=50), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["candidate_applications.id"],
            name=op.f("fk_competition_commission_decisions_application_id_candidate_applications"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["commission_id"],
            ["competition_commissions.id"],
            name=op.f("fk_competition_commission_decisions_commission_id_competition_commissions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competition_commission_decisions")),
        sa.UniqueConstraint(
            "commission_id",
            "application_id",
            name=op.f("uq_competition_commission_decisions_commission_id_application_id"),
        ),
    )
    op.create_table(
        "hiring_cases",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("candidate_application_id", sa.UUID(), nullable=False),
        sa.Column("recruitment_request_id", sa.UUID(), nullable=False),
        sa.Column("staffing_slot_id", sa.UUID(), nullable=False),
        sa.Column("proposed_start_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("process_instance_id", sa.UUID(), nullable=True),
        sa.Column("person_id", sa.Uuid(), nullable=True),
        sa.Column("employee_id", sa.Uuid(), nullable=True),
        sa.Column("assignment_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assignment_id"],
            ["employee_assignments.id"],
            name=op.f("fk_hiring_cases_assignment_id_employee_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["candidate_application_id"],
            ["candidate_applications.id"],
            name=op.f("fk_hiring_cases_candidate_application_id_candidate_applications"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_hiring_cases_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_hiring_cases_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["people.id"],
            name=op.f("fk_hiring_cases_person_id_people"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["process_instance_id"],
            ["process_instances.id"],
            name=op.f("fk_hiring_cases_process_instance_id_process_instances"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recruitment_request_id"],
            ["recruitment_requests.id"],
            name=op.f("fk_hiring_cases_recruitment_request_id_recruitment_requests"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["staffing_slot_id"],
            ["staffing_slots.id"],
            name=op.f("fk_hiring_cases_staffing_slot_id_staffing_slots"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hiring_cases")),
        sa.UniqueConstraint(
            "candidate_application_id", name=op.f("uq_hiring_cases_candidate_application_id")
        ),
    )
    op.create_index(
        op.f("ix_hiring_cases_organization_id"), "hiring_cases", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_hiring_cases_status"), "hiring_cases", ["status"], unique=False)
    op.create_table(
        "interviews",
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("format", sa.String(length=30), nullable=False),
        sa.Column("location_reference", sa.String(length=1000), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("restricted_notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["candidate_applications.id"],
            name=op.f("fk_interviews_application_id_candidate_applications"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interviews")),
    )
    op.create_index(
        op.f("ix_interviews_application_id"), "interviews", ["application_id"], unique=False
    )
    op.create_table(
        "job_offers",
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("position_definition_id", sa.UUID(), nullable=False),
        sa.Column("staffing_slot_id", sa.UUID(), nullable=False),
        sa.Column("proposed_conditions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("proposed_start_date", sa.Date(), nullable=False),
        sa.Column("expiration_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("declined_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decline_reason", sa.Text(), nullable=True),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["candidate_applications.id"],
            name=op.f("fk_job_offers_application_id_candidate_applications"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document_records.id"],
            name=op.f("fk_job_offers_document_id_document_records"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["position_definition_id"],
            ["position_definitions.id"],
            name=op.f("fk_job_offers_position_definition_id_position_definitions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["staffing_slot_id"],
            ["staffing_slots.id"],
            name=op.f("fk_job_offers_staffing_slot_id_staffing_slots"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_offers")),
        sa.UniqueConstraint("application_id", name=op.f("uq_job_offers_application_id")),
    )
    op.create_table(
        "offboarding_waivers",
        sa.Column("offboarding_task_id", sa.UUID(), nullable=False),
        sa.Column("authorized_by_user_id", sa.UUID(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["authorized_by_user_id"],
            ["user_accounts.id"],
            name=op.f("fk_offboarding_waivers_authorized_by_user_id_user_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["offboarding_task_id"],
            ["offboarding_tasks.id"],
            name=op.f("fk_offboarding_waivers_offboarding_task_id_offboarding_tasks"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offboarding_waivers")),
        sa.UniqueConstraint(
            "offboarding_task_id", name=op.f("uq_offboarding_waivers_offboarding_task_id")
        ),
    )
    op.create_table(
        "interview_evaluations",
        sa.Column("interview_id", sa.UUID(), nullable=False),
        sa.Column("interviewer_employee_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("criteria_results", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("recommendation", sa.String(length=50), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("amended_from_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["amended_from_id"],
            ["interview_evaluations.id"],
            name=op.f("fk_interview_evaluations_amended_from_id_interview_evaluations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["interview_id"],
            ["interviews.id"],
            name=op.f("fk_interview_evaluations_interview_id_interviews"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["interviewer_employee_id"],
            ["employees.id"],
            name=op.f("fk_interview_evaluations_interviewer_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interview_evaluations")),
        sa.UniqueConstraint(
            "interview_id",
            "interviewer_employee_id",
            "version_number",
            name=op.f(
                "uq_interview_evaluations_interview_id_interviewer_employee_id_version_number"
            ),
        ),
    )
    op.create_table(
        "interview_participants",
        sa.Column("interview_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_interview_participants_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["interview_id"],
            ["interviews.id"],
            name=op.f("fk_interview_participants_interview_id_interviews"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interview_participants")),
        sa.UniqueConstraint(
            "interview_id",
            "employee_id",
            name=op.f("uq_interview_participants_interview_id_employee_id"),
        ),
    )
    op.create_table(
        "onboarding_tasks",
        sa.Column("hiring_case_id", sa.UUID(), nullable=False),
        sa.Column("task_type", sa.String(length=50), nullable=False),
        sa.Column("assigned_unit_id", sa.UUID(), nullable=True),
        sa.Column("assigned_employee_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completion_evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_employee_id"],
            ["employees.id"],
            name=op.f("fk_onboarding_tasks_assigned_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["assigned_unit_id"],
            ["organization_units.id"],
            name=op.f("fk_onboarding_tasks_assigned_unit_id_organization_units"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["hiring_case_id"],
            ["hiring_cases.id"],
            name=op.f("fk_onboarding_tasks_hiring_case_id_hiring_cases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_onboarding_tasks")),
    )
    op.create_index(
        op.f("ix_onboarding_tasks_hiring_case_id"),
        "onboarding_tasks",
        ["hiring_case_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_onboarding_tasks_hiring_case_id"), table_name="onboarding_tasks")
    op.drop_table("onboarding_tasks")
    op.drop_table("interview_participants")
    op.drop_table("interview_evaluations")
    op.drop_table("offboarding_waivers")
    op.drop_table("job_offers")
    op.drop_index(op.f("ix_interviews_application_id"), table_name="interviews")
    op.drop_table("interviews")
    op.drop_index(op.f("ix_hiring_cases_status"), table_name="hiring_cases")
    op.drop_index(op.f("ix_hiring_cases_organization_id"), table_name="hiring_cases")
    op.drop_table("hiring_cases")
    op.drop_table("competition_commission_decisions")
    op.drop_index(op.f("ix_candidate_screenings_application_id"), table_name="candidate_screenings")
    op.drop_table("candidate_screenings")
    op.drop_table("vacancy_publications")
    op.drop_index(op.f("ix_offboarding_tasks_termination_case_id"), table_name="offboarding_tasks")
    op.drop_table("offboarding_tasks")
    op.drop_index(op.f("ix_candidate_applications_vacancy_id"), table_name="candidate_applications")
    op.drop_index(op.f("ix_candidate_applications_status"), table_name="candidate_applications")
    op.drop_index(
        op.f("ix_candidate_applications_candidate_id"), table_name="candidate_applications"
    )
    op.drop_table("candidate_applications")
    op.drop_index(op.f("ix_vacancies_publication_status"), table_name="vacancies")
    op.drop_index(op.f("ix_vacancies_organization_id"), table_name="vacancies")
    op.drop_table("vacancies")
    op.drop_index(op.f("ix_termination_cases_status"), table_name="termination_cases")
    op.drop_index("ix_termination_cases_scope_status", table_name="termination_cases")
    op.drop_index(op.f("ix_termination_cases_organization_id"), table_name="termination_cases")
    op.drop_index(op.f("ix_termination_cases_employee_id"), table_name="termination_cases")
    op.drop_table("termination_cases")
    op.drop_table("recruitment_staffing_reviews")
    op.drop_index("ix_document_signatures_document", table_name="document_signatures")
    op.drop_table("document_signatures")
    op.drop_table("document_acknowledgements")
    op.drop_table("competition_commission_members")
    op.drop_index(op.f("ix_workflow_tasks_status"), table_name="workflow_tasks")
    op.drop_index(op.f("ix_workflow_tasks_process_instance_id"), table_name="workflow_tasks")
    op.drop_index(op.f("ix_workflow_tasks_assigned_user_id"), table_name="workflow_tasks")
    op.drop_index("ix_workflow_tasks_assigned", table_name="workflow_tasks")
    op.drop_table("workflow_tasks")
    op.drop_index(op.f("ix_recruitment_requests_status"), table_name="recruitment_requests")
    op.drop_index(
        op.f("ix_recruitment_requests_requesting_unit_id"), table_name="recruitment_requests"
    )
    op.drop_index(
        op.f("ix_recruitment_requests_organization_id"), table_name="recruitment_requests"
    )
    op.drop_table("recruitment_requests")
    op.drop_index(
        op.f("ix_process_transition_definitions_definition_version_id"),
        table_name="process_transition_definitions",
    )
    op.drop_table("process_transition_definitions")
    op.drop_index(op.f("ix_document_versions_document_id"), table_name="document_versions")
    op.drop_table("document_versions")
    op.drop_table("document_checklist_items")
    op.drop_table("competition_commissions")
    op.drop_index(
        op.f("ix_process_step_definitions_definition_version_id"),
        table_name="process_step_definitions",
    )
    op.drop_table("process_step_definitions")
    op.drop_index("ix_process_history_instance_time", table_name="process_history_entries")
    op.drop_index(
        op.f("ix_process_history_entries_process_instance_id"), table_name="process_history_entries"
    )
    op.drop_table("process_history_entries")
    op.drop_index("ix_form_submissions_business", table_name="form_submissions")
    op.drop_table("form_submissions")
    op.drop_index(op.f("ix_document_records_status"), table_name="document_records")
    op.drop_index("ix_document_records_process", table_name="document_records")
    op.drop_index(op.f("ix_document_records_organization_id"), table_name="document_records")
    op.drop_index("ix_document_records_business", table_name="document_records")
    op.drop_table("document_records")
    op.drop_index(
        op.f("ix_workflow_actor_rules_definition_version_id"), table_name="workflow_actor_rules"
    )
    op.drop_table("workflow_actor_rules")
    op.drop_index(op.f("ix_process_instances_status"), table_name="process_instances")
    op.drop_index("ix_process_instances_scope_status", table_name="process_instances")
    op.drop_index(op.f("ix_process_instances_organization_id"), table_name="process_instances")
    op.drop_index("ix_process_instances_business", table_name="process_instances")
    op.drop_table("process_instances")
    op.drop_table("form_field_definitions")
    op.drop_index(
        op.f("ix_process_definition_versions_status"), table_name="process_definition_versions"
    )
    op.drop_index(
        op.f("ix_process_definition_versions_process_definition_id"),
        table_name="process_definition_versions",
    )
    op.drop_index(
        "ix_process_definition_versions_effective", table_name="process_definition_versions"
    )
    op.drop_table("process_definition_versions")
    op.drop_table("form_definition_versions")
    op.drop_index(
        op.f("ix_document_template_versions_template_id"), table_name="document_template_versions"
    )
    op.drop_table("document_template_versions")
    op.drop_index(op.f("ix_document_templates_organization_id"), table_name="document_templates")
    op.drop_table("document_templates")
    op.drop_table("vacancy_publication_channels")
    op.drop_table("termination_reasons")
    op.drop_index(op.f("ix_process_definitions_organization_id"), table_name="process_definitions")
    op.drop_table("process_definitions")
    op.drop_table("form_definitions")
    op.drop_index(op.f("ix_document_types_organization_id"), table_name="document_types")
    op.drop_table("document_types")
    op.drop_index("ix_candidates_org_status", table_name="candidates")
    op.drop_table("candidates")
    # ### end Alembic commands ###
